---
title: 웹개발 3일차
date: 2024-05-07 12:00:00 +0800
categories: [웹개발]
tags: [웹개발, try, catch, throw]
math: false
mermaid: true
image:
  path: assets/img/web.png
---

<hr style="border:1px solid white">

## Java로 CRUD 게시판 만들기 #3
- 코드를 작성하다보면 해당 코드가 정상적으로 작동할지, 아니면 오류가 발생할지 예상하기 어려운 경우가 생기는데, 이때 try-catch 을 사용할 수 있다

```java
try {
	String a = "hello world";
    System.out.printf("%d", a);
} catch (NumberFormatException e) {
	System.out.println("명령어가 올바르지 않습니다.");
} catch (Exception e) {
	e.printStackTrace();
	// 오류상황에 대한 자세한 설명					
} finally {
	System.out.println("End");
}
```
- 기본적인 try-catch 문은 위와 같은 형태로 이루어짐
- try 문에 예외가 발생할 가능성이 있는 코드를 넣게됨
- 아래 catch에는 (NumberFormatException e)과 같이 발생가능성이 있는 오류의 형태를 기록하고, 해당 오류 발생시 실행할 코드를 {} 아래에 작성
- 이러한 catch문은 위에서부터 순서대로 진행하게 됨
- 마지막에 있는 finally의 경우 코드가 정상적으로 실행되든, 문제가 발생하든 무조건 실행함

<br/>

```java
try {
    Error err = new Error("에러 생성");
    throw err;
} catch (Error err) {
    System.out.println("메시지 : " + err.getMessage());
    err.printStackTrace();
} finally {
	System.out.println("테스트 종료");
}
```
```
메시지 : 에러 생성
java.lang.Error: 에러 생성
	at Test.main(Test.java:5)
테스트 완료
```
- throw 를 사용하면 일부러 예외상황을 만들 수 있다.
- try 안에서 우리가 만들려고하는 에러 객체를 생성하고, 해당 객체를 throw를 통해서 catch로 던진다.
- 이때 catch에서 우리가 던진 에러 객체를 인식하고 코드를 실행

<br/><br/>

```java
import java.util.List;
import java.util.ArrayList;

public class test {
	static int last_number;
	static List<String> articles;
	
	static {
		articles = new ArrayList<>();
		last_number = 1;
	}

	public static void main(String[] args) {
	}
}
```
- 위 예시에서 last_number와 articles는 main 메서드 안에서 생성된것이 아닌 전역변수이다.
- 일반적으로 전역변수는 생성과 동시에 초기화를 하지않는다. (다만, final은 생성하면서 초기화하지 않으면 사용이 불가능하므로 제외)
- 따라서 따로 초기화를 해줘야하는데, 이들은 static 변수이기 때문에 static 초기화 블럭을 이용해서 초기화한다.